### ISSUE TITLE
Compilation Error in `06_Funktionen.tex`

### ISSUE THREAD

**Issue by Xiphoseer** [d120/vorkurs#14]
I'm currently getting a
```
! Extra \fi.
\__hook_toplevel begindocument ...label \fi } \fi 
                                                  
l.6 \begin{document}
```
error on that document (using `make all`) while testing #13. It seems to happen sometime within the fourth compilation of that file, so the first one with `\def vorkursRecurse` enabled.

As far as I can tell, that prelude is also the issue, because `\def vorkursRecurse` will consume the next token, whatever that is, and use that as the definition content. Changing that to `\def vorkursRecurse {}` seems to do the trick.

**Comment by Rdeisenroth** [comment]
Dieser Fehler wird durch meinen PR gefixed
