### ISSUE TITLE
Lambda Ausdrücke in Übungen

### ISSUE THREAD

**Issue by Rdeisenroth** [d120/vorkurs#26]
In der Lösung zu Übungsblatt 1 Aufgabe 5.1 Wird Lambda, foreach-Schleifen und anderes Zeug was noch nicht eingeführt wurde und teilweise im Vorkurs auch nicht eingeführt wird benutzt
![Screenshot_20211005_235818](https://user-images.githubusercontent.com/53945743/136108510-adaffb9f-8a8d-4a87-9d2c-14c122b11d1a.png)

**Comment by JVHon** [comment]
wird mit meinem nächsten commit behoben (kommt in ein paar Minuten)
