### ISSUE TITLE
py statt python/python3

### ISSUE THREAD

**Issue by UntwistedApple** [d120/vorkurs#31]
Hi,
inzwischen lautet der Befehl, Python auf Windows zu starten, einfach nurnoch "py".

Vielen Dank für Ihre Aufmerksamkeit,
VG
Philipp

**Comment by Rdeisenroth** [comment]
Ist das bei allen Windows versionen so?

last time i checked hat `python` immer noch funktioniert 🤔

**Comment by UntwistedApple** [comment]
Tbh mir wurde gesagt ich soll den Issue erstellen, um jmd daran zu erinnern das zu erwähnen.
Wir hatten gestern oft den Fall, dass der Aufruf von `python` oder `python3` nur den Microsoft Store geöffnet hat (welche Windows Versionen genutzt wurden, weiß ich leider nicht mehr sicher, ich glaube die Mehrzahl hat Win10 genutzt)

`py` war da ein Workaround, um das manuell installierte Python trotzdem zu nutzen.

Denke es ist eine Erwähnung wert, für Menschen, die das Problem mit dem Store haben

**Comment by Xiphoseer** [comment]
> Wir hatten gestern oft den Fall, dass der Aufruf von python oder python3 nur den Microsoft Store geöffnet hat (welche Windows Versionen genutzt wurden, weiß ich leider nicht mehr sicher, ich glaube die Mehrzahl hat Win10 genutzt)

FYI: das ist ein bekanntes Problem, Microsoft hat das automatisch so eingerichtet, siehe https://superuser.com/a/1461471

**Comment by UntwistedApple** [comment]
Good to know, wollt ihr es trotzdem in den Folien erwähnen?

**Comment by Rdeisenroth** [comment]
> Good to know, wollt ihr es trotzdem in den Folien erwähnen?

Ja können wir machen, wahrscheinlich dann für nächstes Jahr

**Comment by Rdeisenroth** [comment]
nicht mehr notwendig, da wir auf Kotlin umsteigen
